[package]
name = "v3-quick-sort"
version = "0.1.0"
authors = ["Alejandro Vásquez Madrid <jose5m45@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
